### ISSUE TITLE
Kicking Things off

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/ruby_course#1]
Alright lads @TheOdinProject/ruby-team lets get this kicked off. 

First thing we need to do is move everything ruby related over from the curriculum repo and change the seeds files on the main site to point the lessons towards their new home in this repo.

**Comment by mindovermiles262** [comment]
The ruby directory in the curriculum is a mess :see_no_evil: 

Let's keep evertything organized in folders:
* Content
  * Follow naming convention: `<url slug>_content.md`
* Projects
  * Follow naming convention: `project_<url slug>`

**Comment by KevinMulhern** [comment]
We need to include the couple of ruby lessons from web dev 101 as well 🙈 
Oh and we will need a place to store new lessons while they are being worked on. We have a few in the curriculum repo that aren't ready for production yet.

**Comment by mindovermiles262** [comment]
> We need to include the couple of ruby lessons from web dev 101

Easy - we add a web dev 101 folder to the lessons and projects folder

> we will need a place to store new lessons while they are being worked on

Make an `In Progress` folder inside of `Lessons`

**Comment by KevinMulhern** [comment]
Sounds good to me 😄

**Comment by leosoaivan** [comment]
Sgtm

**Comment by KevinMulhern** [comment]
Just had a thought 🙈 
Would it make more sense to structure it as it is in on the site? a folder for each section.

Something like:

* web_development_101
  * the_backend
* ruby_programming
  * basic_ruby
  * intermediate_ruby
  * ...

I figure it would make it easier to find a specific lesson when your looking for it. This is obviously up for discussion though.

Oh, I really like the naming converstion you've outlined ❤️

**Comment by KevinMulhern** [comment]
@TheOdinProject/ruby-team pls discuss, we need to make a decision on this before we can move this forward.

**Comment by mindovermiles262** [comment]
@KevinMulhern I agree with your directory structure.

- web_dev_101 (dir)
  - the_backend (dir)
    - lesson_title_here01.md
    - lesson_title_here02.md
    - project_title_here.md
- ruby_programming (dir)
  - basic_ruby (dir)
    - lesson_title_here.md
    - project_title_here.md

**Comment by KevinMulhern** [comment]
lets do it 😄
