### ISSUE TITLE
First long term project

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/ruby_course#11]
Now that we have moved all the files over I think It would be a good idea to decide upon the first long term project we will work on.

While we are trying to get the course to match the syllabus we drafted up, a long term project can be one of the sections of the new syllabus.

We will of course create issues and work on other smaller things as they come up while we work on a longer term project.

**Comment by KevinMulhern** [comment]
My votes goes for the basic OOP section https://github.com/TheOdinProject/ruby_course/blob/master/Syllabus.md#section-basics-of-oop

It won't affect any other course, can directly replace the lessons already there for OOP and will improve the Ruby course tremendously.

**Comment by mindovermiles262** [comment]
Vote: TDD

We currently don't have a TDD section and it's most needed

**Comment by CouchofTomato** [comment]
How many of us are there? Can we not split our time effectively between maybe two sections?

If I had to pick one I'd say OOP.

**Comment by KevinMulhern** [comment]
I'd be happy enough with two on the go, theres 4 of us so there might not be much left over over for outside contributors if we are working on one at a time.

@leosoaivan @mindovermiles262 would you guys be happy with having 2 sections being worked on at a time?

**Comment by mindovermiles262** [comment]
SGTM :+1:

**Comment by CouchofTomato** [comment]
Great. What's the plan to get started then?

**Comment by KevinMulhern** [comment]
Get some stub templates made out for each lesson in those sections and make issues for them?

**Comment by CouchofTomato** [comment]
So as per the syllabus we need to create a basics of OOP folder and then create a file for each prospective lesson?

**Comment by KevinMulhern** [comment]
Yeah pretty much, just a stub file that has the basic template for a lesson. Having the file already created and the basic structure in place for it will hopefully remove a barrier for outside contributors to take part.

**Comment by KevinMulhern** [comment]
derp

@TheOdinProject/ruby-team I forgot to mention I've made a bunch of issues for these two sections. Please feel free to claim any that piques your interest. I'm going to make some posts in various ruby community channels to see if people in the community are interested in helping us with this.
