### ISSUE TITLE
Files and Serialisation  Lessons

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/ruby_course#115]
We are seeking people to take charge of coordinating the creation of these lessons. If you would like to fill take this role, please let us know by commenting on this issue with your desire take ownership of these lessons.

For each lesson, reply to this issue with:

1. An Introduction for the lesson
A brief summary about what the lesson is about and why the topics or concepts it teaches are important.

2. Learning Outcomes
A list of bullet points of what the student is expected to know or be able to do by the end of this lesson

2. Content for the lesson
Explanations of the main concepts in the lesson, include code snippets and easy to understand metaphors where applicable.

3. Assignment
Either a list of links to resources the user will go through to learn about the topic of this lesson more in depth. Have no more than 5 resources, ideally no more than three. Or an exercise the student should do to solidify their understanding of the lesson content.

4. Additional Resources
A list of links  to other resources which are valuable and or complement the assignment resources. Link to no more than three additional resources to avoid this section becoming too cluttered.

---

List of lessons: 

- [ ] File Basics - The basics of using files in Ruby, open, reading, writing and closing.
- [ ] Loading files - Require, load, require_relative etc
- [ ] Standard Ruby project set up - How to set up your ruby objects, lib and spec folder etc
- [ ] Serialization - Yaml and JSON.

**Comment by Mycroft1891** [comment]
regarding the project of this lesson. If you use download the `event_attendees.csv` file using the link from the lesson, you don't get the actual `csv` but the `html` file. To get the actual csv you have to use the raw link:

https://raw.githubusercontent.com/TheOdinProject/ruby_course/master/ruby_programming/intermediate_ruby/event_attendees.csv

**Comment by mindovermiles262** [comment]
Hi @Mycroft1891,
The like is set to the URL you've provided.  However, opening it in a web browser will forward you to the github page (We have no control over this)

In the tutorial, i believe it tells you to use `curl` to download the file:

    curl -o event_attendees.csv https://github.com/TheOdinProject/ruby_course/tree/master/ruby_programming/intermediate_ruby/event_attendees.csv

which will download the file into the current directory.

**Comment by Mycroft1891** [comment]
@mindovermiles262 Yes, I ran that exact command but when I open the `event_attendees.csv` file it is an HTML file not CSV file. Try it out on your machine.

**Comment by KevinMulhern** [comment]
@Mycroft1891 Can you open a new issue for this please? this is issue for discussing and coordinating the redevelopment of this section.

**Comment by Mycroft1891** [comment]
@KevinMulhern Sure

**Comment by KevinMulhern** [comment]
@Mycroft1891 Thank you 😄
