### ISSUE TITLE
Intermediate Object Oriented Programming Lessons

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/ruby_course#116]
We are seeking people to take charge of coordinating the creation of these lessons. If you would like to fill take this role, please let us know by commenting on this issue with your desire take ownership of these lessons.

For each lesson, reply to this issue with:

1. An Introduction for the lesson
A brief summary about what the lesson is about and why the topics or concepts it teaches are important.

2. Learning Outcomes
A list of bullet points of what the student is expected to know or be able to do by the end of this lesson

2. Content for the lesson
Explanations of the main concepts in the lesson, include code snippets and easy to understand metaphors where applicable.

3. Assignment
Either a list of links to resources the user will go through to learn about the topic of this lesson more in depth. Have no more than 5 resources, ideally no more than three. Or an exercise the student should do to solidify their understanding of the lesson content.

4. Additional Resources
A list of links  to other resources which are valuable and or complement the assignment resources. Link to no more than three additional resources to avoid this section becoming too cluttered.

---

List of lessons: 

- [ ] The Ruby Object Model - How classes are structured under the hood and how ruby finds which method to use.
- [ ] Solid Design Principles - Explain all the principles of SOLID and how they make your code better.
- [ ] Basics of Refactoring and code smells - Basic code smells and solutions for refactoring them
- [ ] Composition over Inheritance - Why you should use composition over inheritance.
- [ ] Basic Design Patterns - Some of the common design patterns the student will come across in code bases.

**Comment by heyalvaro** [comment]
Hello! I'd like to take ownership of these lessons

**Comment by KevinMulhern** [comment]
Hi again @heyalvaro, the same applies to these lessons. Sorry yet again for not replying to this one sooner.
