### ISSUE TITLE
Advanced Ruby Lessons

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/ruby_course#117]
We are seeking people to take charge of coordinating the creation of these lessons. If you would like to fill take this role, please let us know by commenting on this issue with your desire take ownership of these lessons.

For each lesson, reply to this issue with:

1. An Introduction for the lesson
A brief summary about what the lesson is about and why the topics or concepts it teaches are important.

2. Learning Outcomes
A list of bullet points of what the student is expected to know or be able to do by the end of this lesson

2. Content for the lesson
Explanations of the main concepts in the lesson, include code snippets and easy to understand metaphors where applicable.

3. Assignment
Either a list of links to resources the user will go through to learn about the topic of this lesson more in depth. Have no more than 5 resources, ideally no more than three. Or an exercise the student should do to solidify their understanding of the lesson content.

4. Additional Resources
A list of links  to other resources which are valuable and or complement the assignment resources. Link to no more than three additional resources to avoid this section becoming too cluttered.

---

List of lessons: 

- [ ] Blocks Procs and lambdas- What these are and how to use them.
- [ ] Advanced Enumerable’s- How to use enumerable in your own classes.
- [ ] Meta Programming basics - What is metaprogramming and what are some of the basic things you can do with it?

**Comment by heyalvaro** [comment]
Hello Kevin! I'd like to take ownership of these lessons

**Comment by KevinMulhern** [comment]
Hey @heyalvaro, sorry I'm just seeing this. I was very busy with IRL stuff the past few months and missed quite a few comments on issues :( 

I'm going through everything at the moment and trying to get things organised 😄 we are going to hold off on these set of lessons for now and come back to them when we get  more of the foundational lessons out.

These are the priorty lessons at the moment https://github.com/TheOdinProject/ruby_course/issues/112

Sorry again for not replying sooner.
