### ISSUE TITLE
Change Link in Event Manager Project

### ISSUE THREAD

**Issue by Mycroft1891** [TheOdinProject/ruby_course#120]
Regarding the project of this lesson. If you use download the event_attendees.csv file using the link from the lesson, you don't get the actual csv but the html file. To get the actual csv you have to use the raw link:

https://raw.githubusercontent.com/TheOdinProject/ruby_course/master/ruby_programming/intermediate_ruby/event_attendees.csv

@mindovermiles262 pointed out that the URL is correct in the project's readme but If you take a look at the lesson.md for this project: https://github.com/TheOdinProject/ruby_course/blob/master/ruby_programming/intermediate_ruby/project_event_manager.md

You will see that the link doesn't point to the raw CSV file but the regular CSV file.

This should be an easy fix.

PS: On this line in the lesson:
```
response = civic_info.representative_info_by_address(address: 80202, levels: 'country', roles: ['legislatorUpperBody', legislatorLowerBody'])
```

there is a missing `'` for `legislatorLowerBody`

**Comment by KevinMulhern** [comment]
Thanks for reporting this @Mycroft1891

**Comment by mindovermiles262** [comment]
Corrected.

Thanks @Mycroft1891 for pointing this out 😄
