### ISSUE TITLE
Advanced Ruby Building blocks resource links Amazon page

### ISSUE THREAD

**Issue by Javier-Machin** [TheOdinProject/ruby_course#178]
Second assignment [here](https://github.com/TheOdinProject/ruby_course/blob/master/ruby_programming/basic_ruby/lesson_advanced_building_blocks.md) goes to an Amazon page to buy the book, I don't think that was intended :)

**Comment by Javier-Machin** [comment]
(This)[https://books.google.es/books?id=VCQGjDhhbn8C&lpg=PA27&hl=es&pg=PA48#v=onepage&q&f=false] might be the correct link, but that preview has some omitted pages.

**Comment by CouchofTomato** [comment]
Hey @Javier-Machin 

The book itself is not free, and unfortunately there isn't really a great free resource we've found that we could replace it with. That's why it's linked to Amazon I believe.

**Comment by Javier-Machin** [comment]
I see, maybe it can be changed to the second link then, its the same book but it goes directly to it and the  quality seems to be a bit better, I don't know if the omitted pages are the same in both.

**Comment by Javier-Machin** [comment]
Jonathan Yiv found this: 
https://github.com/randytorres/Books/blob/master/Apress-Beginning%20Ruby%20-%20From%20Novice%20to%20Professional.pdf
Seems to be the full book, but maybe its a bit shady to link that?

**Comment by mindovermiles262** [comment]
>  shady to link that

Exactly. We, as an open source project, cannot support pirating of copyrighted materials
