### ISSUE TITLE
Small Wins

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/ruby_course#2]
Are there any small things you think we can do to improve the course right away?
This is the place to list and discuss them.

**Comment by mindovermiles262** [comment]
Let's get a project set up for the ruby course

**Comment by KevinMulhern** [comment]
Heres some of the small wins I think we can do:

* Create a rake task we can run on the main site to get lesson completion data for lessons in this course on a weekly/daily basis.
* Go through the resources we are using in this course and update them with newer/better resources if any exist.
* Split any projects out into separate files (this is a blocker for the student submissions feature)

**Comment by leosoaivan** [comment]
I know we had started redoing the curriculum a while back. How about drafting a syllabus? A broad overview would be like good design: the implementation will naturally follow :)

**Comment by KevinMulhern** [comment]
Good idea @leosoaivan 😄 I think that falls under long term projects better https://github.com/TheOdinProject/ruby_course/issues/3

**Comment by CouchofTomato** [comment]
I think the best thing we can do right now is update resources. I'll start going through what we have and see whats out of date.

**Comment by KevinMulhern** [comment]
Another small project we could work on is experimenting with using repl.it for exercises in a lesson.
