### ISSUE TITLE
Lesson: Introduction to Object Oriented Programming

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/ruby_course#24]
This lesson should teach the student the following:
* What is OOP and why it came about
* History of OOP
* The problem it solves

Please use this [stub file](https://github.com/TheOdinProject/ruby_course/blob/master/ruby_programming/oop_basics/oop_introduction_lesson.md) for the lesson

---
### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

**Comment by CouchofTomato** [comment]
I'll take this one.

**Comment by MariaTikhonova** [comment]
I would write text to this section and propose to your consideration if its still relevant and you approve.

**Comment by KevinMulhern** [comment]
Hey @MariaTikhonova, thanks for taking this on 😄 I'm looking forward to seeing what you put together.

**Comment by KevinMulhern** [comment]
Hey @MariaTikhonova, we are doing a bit of a restruture with how we are organizing the redevelopment of the course. This lesson falls under this issue now https://github.com/TheOdinProject/ruby_course/issues/113

If you're still working on this lesson, please continue to do so 😄 just comment with the lesson content in that linked issue when you're done.

Let me know if you have any questions

**Comment by MariaTikhonova** [comment]
Hi,@KevinMulhern ! I'm working on this lesson, and will I get to the stage
I will see it looks the  proper way to show you ( several days), I will
write you a message for checking advise first :) . And then go on refining
or push ( comment).
