### ISSUE TITLE
Lesson: Introduction to Test Driven Development

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/ruby_course#32]
This lesson should teach the student the following:
* What is TDD
* What problems does it solve?
* Red, green, refactor cycle 

Please use this [stub file](https://github.com/TheOdinProject/ruby_course/blob/master/ruby_programming/test_driven_development/tdd_introduction_lesson.md) for the lesson

---
### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

**Comment by mindovermiles262** [comment]
Staking Claim

**Comment by KevinMulhern** [comment]
I moved this lesson under this issue @mindovermiles262, to try out the new way of organising this re-development. https://github.com/TheOdinProject/ruby_course/issues/114
