### ISSUE TITLE
Event Manager

### ISSUE THREAD

**Issue by sarthak-v** [TheOdinProject/ruby_course#321]
Please someone important review this section, it surely needs some work. For example, at many places the code seemed complete but gave an error when i ran it, because it was incomplete. If its not complete on purpose then atleast state that, and at some places the code is formated as simple text.

**Comment by KevinMulhern** [comment]
Hey @sarthak-v, can you be a bit more specific with whats broken please?

Can you provide some example of which parts you ran and got an error and what the error was?

**Comment by sarthak-v** [comment]
![screenshot from 2018-05-27 07-58-42](https://user-images.githubusercontent.com/38680527/40581943-dff84dec-6183-11e8-8552-8c52adaa51b0.png)
https://www.theodinproject.com/courses/ruby-programming/lessons/event-manager

**Comment by sarthak-v** [comment]
![screenshot from 2018-05-27 08-02-08](https://user-images.githubusercontent.com/38680527/40581960-46e0b864-6184-11e8-89c6-3ca8e7c21c0e.png)
code in this section (ERB) is not working as stated.

**Comment by KevinMulhern** [comment]
Thanks @sarthak-v, the code high lighting should be easy enough to fix. I'll create a separate issue for that.

As for the erb section, can you tell use the specific error you were getting with it? that will help us narrow down the debugging.

**Comment by sarthak-v** [comment]
The code is wrongly replacing the legislators in the form. Its showing that rescue text even when the info is available.

**Comment by KevinMulhern** [comment]
Hey @sarthak-v, did that PR you made address the problems here? what about the issue with erb code snippet? 😄

**Comment by sarthak-v** [comment]
i will update all the incorrect codes(if there are, other than erb code) by today or tmrw

**Comment by sarthak-v** [comment]
everything's working fine
