### ISSUE TITLE
broken link?

### ISSUE THREAD

**Issue by usmanakhter** [TheOdinProject/ruby_course#326]
first sentence [Web Dev 101 course](https://www.theodinproject.com/web-development-101/ruby-basics) goes to 404 page instead of [here](https://www.theodinproject.com/courses/web-development-101)

**Comment by mindovermiles262** [comment]
Which page is this on, @usmanakhter ?

**Comment by usmanakhter** [comment]
oh sorry, on [Ruby Building BLocks](https://www.theodinproject.com/courses/ruby-programming/lessons/ruby-building-blocks)

**Comment by CouchofTomato** [comment]
Hi @usmanakhter 

You are welcome to submit a pull request if you'd like to make the fix otherwise we can handle it ourselves. Let me know what you'd prefer.

**Comment by usmanakhter** [comment]
looks like it got taken care of thanks

**Comment by sarthak-v** [comment]
maybe u should close this issue now
