### ISSUE TITLE
Lesson: Introduction to RSpec

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/ruby_course#33]
This lesson should teach the student the following:
* What is RSpec?
* How to install RSpec
* Basics RSpec syntax
  * describe
  * subject and let
  * it

Please use this [stub file](https://github.com/TheOdinProject/ruby_course/blob/master/ruby_programming/test_driven_development/rspec_introduction_lesson.md) for the lesson

---
### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

**Comment by leosoaivan** [comment]
I'll start us off with this one!

**Comment by KevinMulhern** [comment]
@leosoaivan completed this one 💪 🎉
