### ISSUE TITLE
"Beginning Ruby" resource has missing pages

### ISSUE THREAD

**Issue by benjsmyth** [TheOdinProject/ruby_course#368]
Going through the Basic Ruby section, I've noticed that the link to the resource for [Beginning Ruby](https://books.google.com.pk/books?id=MiGpDAAAQBAJ&printsec=frontcover#v=onepage&q&f=false) by Peter Cooper is not a complete copy of the book and has some pages removed. Some of these removed pages are included in what we are told to read.

I did some searching and found [this](http://index-of.es/Ruby/Begining%20Ruby-1.9.pdf) PDF which I believe should be used instead, as it has the full book uploaded. It is also the same edition as the one already used in this lesson.

**Comment by AREEBAISHTIAQ** [comment]
@benjsmyth  the link you have found is "second edition" and in lesson there is  "third edition" of "beginning ruby", there is no link of this book with full pages

**Comment by KevinMulhern** [comment]
Bear in mind whatever we link to needs to be legal as well. We definitley do not want to be linking to anything that violates copy right infringement laws.

The ruby course is due a refresh in terms of resources, theres some new free resources that may be more suitable than Beginning Ruby.

**Comment by benjsmyth** [comment]
My mistake, I had thought they were the same edition. Also hadn't considered legal issues. Thank you both for you responses.
