### ISSUE TITLE
Remove testing lesson on web dev 101

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/ruby_course#4]
This has been coming up quite a lot in chat :point_up: [October 26, 2017 8:40 PM](https://gitter.im/TheOdinProject/theodinproject?at=59f23a1f5a1758ed0f52d3ac)

We had to remove the rspec course by codeschool from the testing lesson on web dev 101 https://www.theodinproject.com/courses/web-development-101/lessons/testing-basics

Without that course the lesson is basically useless, its too early in the curriculum to be going over testing anyway.

The solution to this problem is to remove this testing lesson from the curriculum. I believe that removing this lesson will have a positive effect on the curriculum as a whole.

Tasks include
* Remove the lesson from the seeds file in the main site
* Remove any mentions of this lesson in other parts of the course. I think its mentioned in the ruby course and the rails course.

**Comment by leosoaivan** [comment]
I can't self assign from mobile, but I'll look at this. I'm good at deleting stuff.

**Comment by leosoaivan** [comment]
I am running into many instances of RSpec being mentioned as the testing framework for Hartl's tutorial. I'm fixing those as well.
