### ISSUE TITLE
Intermediate Ruby/OOP: Links to eBook 

### ISSUE THREAD

**Issue by hoangtommy** [TheOdinProject/ruby_course#497]
Hey team,

The links in the Beginning Ruby book are linking out to an [Amazon page](https://www.amazon.co.uk/Beginning-Ruby-Professional-Peter-Cooper/dp/1484212797) to purchase the book whereas in previous sections, it was linking to the [ebook preview itself](https://books.google.com.pk/books?id=MiGpDAAAQBAJ&printsec=frontcover#v=onepage&q&f=false).

Happy to fix the links myself but was wondering if there were legal issues or other reasons why we're linking out to Amazon instead of a free albeit pirated version of the book.

**Comment by KevinMulhern** [comment]
Hi @hoangtommy, I think at the time we were updating the links the google previews of those chapters were not available.

We've been considering updating the resources on that section for a while now. I think this short book would be better for the OOP section: https://launchschool.com/books/oo_ruby/read/introduction

**Comment by hoangtommy** [comment]
Ahh gotcha. I can update the current links to the google previews as a temporary solution if that would be helpful. 

Would you suggest I read the shorter book, the existing book, or both as someone following the curriculum for the first time?

**Comment by hoangtommy** [comment]
I ended up doing both. I agree with you Kevin, the Launch School resource is more concise and was a better read IMO. I'll do a pull request to include the Launch School as an additional resource for now and update the links for the original google preview book.
